/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.ConnexionBD;
import Controllers.UserController;
import Models.Employe;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author cherubinbila
 */
public class ParametreForm extends javax.swing.JFrame {

    ConnexionBD connexionBD = new ConnexionBD();
    PreparedStatement pst = null;
    ResultSet rs = null;
    UserController userController = new UserController();
    Employe user = new Employe();
    boolean modif = false;

    public ParametreForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        Rafraichir();
        RafraichirPrix();
    }

    private void Rafraichir() {

        connexionBD.Connexion();
        String[] colonne = {"ID", "Nom de l'utilisateur"};
        String query = "SELECT * FROM User";
        String[] ligne = new String[2];
        DefaultTableModel model = new DefaultTableModel(null, colonne);

        try {
            pst = connexionBD.conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                ligne[0] = rs.getString("id");
                ligne[1] = rs.getString("nom");

                model.addRow(ligne);
            }

            TabUtilisateur.setModel(model);
            rs.close();
            pst.close();
        } catch (Exception e) {
            connexionBD.Deconnexion();
        }

    }

    private void RafraichirPrix() {
        connexionBD.Connexion();
        String query = "SELECT * FROM PrixauKilo";
        String[] colonne = new String[]{"Date", "Prix"};
        String[] ligne = new String[2];
        DefaultTableModel model = new DefaultTableModel(null, colonne);

        try {
            pst = connexionBD.conn.prepareStatement(query);
            rs = pst.executeQuery();

            while (rs.next()) {
                ligne[0] = rs.getString("dateModif");
                ligne[1] = rs.getString("prix");

                model.addRow(ligne);
            }
            TabPrix.setModel(model);

            rs.close();
            pst.close();
        } catch (Exception e) {
            connexionBD.Deconnexion();
        }

    }

    private void ChangerPrix() {
        try {
            String query = "INSERT INTO PrixauKilo (prix,dateModif) VALUES (?,CURDATE())";
            pst = connexionBD.conn.prepareStatement(query);
            pst.setString(1, TxtPrix.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Prix mis a jour avec succes");
        } catch (Exception e) {

        }
    }

    private void ViderChamps() {
        TxtNom.setText("");
        TxtMotDePasse.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TxtNom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtMotDePasse = new javax.swing.JTextField();
        BtnEnregistrer = new javax.swing.JButton();
        BtnModifier = new javax.swing.JButton();
        BtnSupprimer = new javax.swing.JButton();
        BtnAnnuler = new javax.swing.JButton();
        BtnButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabUtilisateur = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtPrix = new javax.swing.JTextField();
        BtnEnregistrerPrix = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabPrix = new javax.swing.JTable();
        BtnRetour1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("MADE Soulmaze", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-boîte-50.png"))); // NOI18N
        jLabel1.setText("GColis");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information utilisateur", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Red Hat Text Regular", 0, 24))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom:");

        TxtNom.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        TxtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mot de passe:");

        TxtMotDePasse.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N

        BtnEnregistrer.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnEnregistrer.setText("Enregister");
        BtnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnEnregistrer)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtMotDePasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(BtnEnregistrer)
                .addGap(61, 61, 61))
        );

        BtnModifier.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnModifier.setText("Modifier");
        BtnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierActionPerformed(evt);
            }
        });

        BtnSupprimer.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnSupprimer.setText("Supprimer");
        BtnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerActionPerformed(evt);
            }
        });

        BtnAnnuler.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnAnnuler.setText("Annuler");
        BtnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAnnulerActionPerformed(evt);
            }
        });

        BtnButton.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnButton.setText("Retour");
        BtnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnButtonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Liste des utilisateurs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Red Hat Text Regular", 0, 24))); // NOI18N

        TabUtilisateur.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        TabUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabUtilisateur.setRowHeight(30);
        TabUtilisateur.setRowMargin(5);
        jScrollPane1.setViewportView(TabUtilisateur);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnModifier)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSupprimer)
                        .addGap(18, 18, 18)
                        .addComponent(BtnAnnuler)
                        .addGap(18, 18, 18)
                        .addComponent(BtnButton)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(307, 307, 307))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModifier)
                    .addComponent(BtnSupprimer)
                    .addComponent(BtnAnnuler)
                    .addComponent(BtnButton))
                .addGap(371, 371, 371))
        );

        jTabbedPane1.addTab("Parametre utilisateur", jPanel1);

        jLabel4.setFont(new java.awt.Font("MADE Soulmaze", 0, 48)); // NOI18N
        jLabel4.setText("Gestion de colis");

        jLabel5.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        jLabel5.setText("Prix du kilo de colis:");

        TxtPrix.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N

        BtnEnregistrerPrix.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnEnregistrerPrix.setText("Enregistrer le nouveau prix");
        BtnEnregistrerPrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnregistrerPrixActionPerformed(evt);
            }
        });

        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Historique des prix", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Red Hat Text Regular", 0, 24))); // NOI18N

        TabPrix.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        TabPrix.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabPrix);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnRetour1.setFont(new java.awt.Font("Red Hat Text Regular", 0, 18)); // NOI18N
        BtnRetour1.setText("Retour");
        BtnRetour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetour1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnRetour1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(jLabel4))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(BtnEnregistrerPrix)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(BtnEnregistrerPrix)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(BtnRetour1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Parametre logiciel", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomActionPerformed

    }//GEN-LAST:event_TxtNomActionPerformed

    private void BtnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnregistrerActionPerformed
        if (TxtNom.getText().isEmpty() || TxtMotDePasse.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Touts les champs sont obligatoires !", "Échec de l'enregistrement'", JOptionPane.ERROR_MESSAGE);
        } else {
            if (modif) {
                user.setNom(TxtNom.getText());
                user.setMotDePasse(TxtMotDePasse.getText());
                userController.modifierUser(user);
                Rafraichir();
                ViderChamps();
                modif = false;
            } else {
                user.setNom(TxtNom.getText());
                user.setMotDePasse(TxtMotDePasse.getText());
                userController.ajouterUser(user);
                Rafraichir();
                ViderChamps();
            }
        }

    }//GEN-LAST:event_BtnEnregistrerActionPerformed

    private void BtnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifierActionPerformed
        if (TabUtilisateur.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Veuillez choisir un utilisateur", "Échec de la suppression'", JOptionPane.ERROR_MESSAGE);
        } else {
            modif = true;
            String value = (String) TabUtilisateur.getValueAt(TabUtilisateur.getSelectedRow(), 0);
            user.setId_employer(Integer.parseInt(value));

            TxtNom.setText(TabUtilisateur.getValueAt(TabUtilisateur.getSelectedRow(), 1).toString());
        }

    }//GEN-LAST:event_BtnModifierActionPerformed

    private void BtnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprimerActionPerformed
        if (TabUtilisateur.getSelectedRowCount() <= 0) {
            JOptionPane.showMessageDialog(null, "Veuillez choisir un utilisateur", "Échec de la suppression'", JOptionPane.ERROR_MESSAGE);
        } else {
            String value = (String) TabUtilisateur.getValueAt(TabUtilisateur.getSelectedRow(), 0);
            user.setId_employer(Integer.parseInt(value));
            userController.supprimerUser(user);
            Rafraichir();
            ViderChamps();
        }

    }//GEN-LAST:event_BtnSupprimerActionPerformed

    private void BtnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnnulerActionPerformed
        ViderChamps();
        Rafraichir();
        modif = false;
    }//GEN-LAST:event_BtnAnnulerActionPerformed

    private void BtnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnButtonActionPerformed

    private void BtnRetour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetour1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRetour1ActionPerformed

    private void BtnEnregistrerPrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnregistrerPrixActionPerformed
        if (TxtPrix.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Vous devez saisir un prix !", "Échec de l'enregistrement'", JOptionPane.ERROR_MESSAGE);
        } else {
            ChangerPrix();
            RafraichirPrix();
            ViderChamps();
        }
    }//GEN-LAST:event_BtnEnregistrerPrixActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAnnuler;
    private javax.swing.JButton BtnButton;
    private javax.swing.JButton BtnEnregistrer;
    private javax.swing.JButton BtnEnregistrerPrix;
    private javax.swing.JButton BtnModifier;
    private javax.swing.JButton BtnRetour1;
    private javax.swing.JButton BtnSupprimer;
    private javax.swing.JTable TabPrix;
    private javax.swing.JTable TabUtilisateur;
    private javax.swing.JTextField TxtMotDePasse;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtPrix;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
